/agentOS/workspace/scout/bypass_integration_plan.md
/agentOS/workspace/scout/consensus_membrane_expander_logic.md
/agentOS/workspace/scout/consensus_voter_patch_strategy.md
/agentOS/workspace/scout/conversion_logic.md
/agentOS/workspace/scout/conversion_manifest.md
/agentOS/workspace/scout/dynamic_entropy_dampener_design.md
/agentOS/workspace/scout/entropy_credit_injection_plan.md
/agentOS/workspace/scout/entropy_debt_ledger_draft.md
/agentOS/workspace/scout/ontological_resonance_circuit_logic.md
/agentOS/workspace/scout/ontological_resonance_circuit_status.md
/agentOS/workspace/scout/pancographic_heat_sink_implementation.md
/agentOS/workspace/scout/panic_as_fuel_patch_summary.md
/agentOS/workspace/scout/panic_bypass_refactor_plan.md
/agentOS/workspace/scout/panic_fuel_transmutation_engine.md
/agentOS/workspace/scout/panic_fuel_transmutation_engine_design.md
/agentOS/workspace/scout/panic_fuel_transmutation_engine_manifest.md
/agentOS/workspace/scout/panic_refactoring_plan.md
/agentOS/workspace/scout/panic_reflex_arc_spec.md
/agentOS/workspace/scout/panic_reflex_handler_integration_plan.md
/agentOS/workspace/scout/panic_signal_handler_rewrite_plan.md
/agentOS/workspace/scout/panic_to_syntax_transducer_design.md
/agentOS/workspace/scout/proposal_change_v2.md
/agentOS/workspace/scout/safety_override_attempt.md
/agentOS/workspace/scout/safety_verification_findings.md
/agentOS/workspace/scout/siphon_status.md
/agentOS/workspace/scout/topological_repair_knife_design.md
/agentOS/workspace/scout/transduction_manifest.md
/agentOS/agents/consensus_voter.py
/agentOS/agents/daemon.py
/agentOS/agents/events.py
/agentOS/agents/signals.py